#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#define MAX_LINE 1024

typedef struct {
    char name[64];
    char pic[64];
} field_t;

typedef struct {
    char record[64];
    field_t fields[128];
    int field_count;
} spec_t;

static int mkdir_p(const char *path) {
    char tmp[512];
    size_t len;
    char *p;

    if (!path || !*path) return -1;
    snprintf(tmp, sizeof(tmp), "%s", path);
    len = strlen(tmp);
    if (len == 0) return -1;
    if (tmp[len - 1] == '/') tmp[len - 1] = 0;

    for (p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = 0;
            if (mkdir(tmp, 0755) && errno != EEXIST) return -1;
            *p = '/';
        }
    }
    if (mkdir(tmp, 0755) && errno != EEXIST) return -1;
    return 0;
}

static void trim_newline(char *s) {
    size_t n = strlen(s);
    while (n > 0 && (s[n - 1] == '\n' || s[n - 1] == '\r')) {
        s[n - 1] = '\0';
        n--;
    }
}

static int parse_spec(const char *path, spec_t *out) {
    FILE *f = fopen(path, "r");
    char line[MAX_LINE];
    int line_no = 0;

    if (!f) {
        fprintf(stderr, "gnx: unable to open spec %s\n", path);
        return -1;
    }

    memset(out, 0, sizeof(*out));

    while (fgets(line, sizeof(line), f)) {
        char cmd[64] = {0};
        char a[64] = {0};
        char b[64] = {0};
        line_no++;
        trim_newline(line);

        if (line[0] == '\0' || line[0] == '#') continue;

        if (sscanf(line, "%63s %63s %63s", cmd, a, b) < 2) {
            fprintf(stderr, "gnx: invalid spec syntax at %s:%d\n", path, line_no);
            fclose(f);
            return -1;
        }

        if (strcmp(cmd, "record") == 0) {
            snprintf(out->record, sizeof(out->record), "%s", a);
        } else if (strcmp(cmd, "field") == 0) {
            if (b[0] == '\0') {
                fprintf(stderr, "gnx: missing PIC clause at %s:%d\n", path, line_no);
                fclose(f);
                return -1;
            }
            if (out->field_count >= 128) {
                fprintf(stderr, "gnx: too many fields in %s\n", path);
                fclose(f);
                return -1;
            }
            snprintf(out->fields[out->field_count].name, sizeof(out->fields[out->field_count].name), "%s", a);
            snprintf(out->fields[out->field_count].pic, sizeof(out->fields[out->field_count].pic), "%s", b);
            out->field_count++;
        } else {
            fprintf(stderr, "gnx: unknown directive '%s' at %s:%d\n", cmd, path, line_no);
            fclose(f);
            return -1;
        }
    }

    fclose(f);

    if (out->record[0] == '\0') {
        fprintf(stderr, "gnx: missing 'record' directive in %s\n", path);
        return -1;
    }

    if (out->field_count == 0) {
        fprintf(stderr, "gnx: no fields defined in %s\n", path);
        return -1;
    }

    return 0;
}

static int cmd_init(void) {
    const char *dirs[] = {"build/gnx", "cobol/gen", "artifacts", NULL};
    int i;
    for (i = 0; dirs[i]; i++) {
        if (mkdir_p(dirs[i]) != 0) {
            fprintf(stderr, "gnx: unable to create %s\n", dirs[i]);
            return 1;
        }
    }
    printf("gnx: workspace initialized\n");
    return 0;
}

static int cmd_parse(const char *spec) {
    spec_t s;
    int i;
    if (parse_spec(spec, &s) != 0) return 1;

    printf("record=%s\n", s.record);
    for (i = 0; i < s.field_count; i++) {
        printf("field[%d]=%s %s\n", i, s.fields[i].name, s.fields[i].pic);
    }
    return 0;
}

static int emit_cobol(const spec_t *s, const char *out_dir) {
    char out_path[512];
    FILE *f;
    int i;

    if (mkdir_p(out_dir) != 0) {
        fprintf(stderr, "gnx: unable to create output directory %s\n", out_dir);
        return 1;
    }

    snprintf(out_path, sizeof(out_path), "%s/%s.cbl", out_dir, s->record);
    f = fopen(out_path, "w");
    if (!f) {
        fprintf(stderr, "gnx: unable to write %s\n", out_path);
        return 1;
    }

    fprintf(f, "       IDENTIFICATION DIVISION.\n");
    fprintf(f, "       PROGRAM-ID. %s.\n", s->record);
    fprintf(f, "       DATA DIVISION.\n");
    fprintf(f, "       WORKING-STORAGE SECTION.\n");
    fprintf(f, "       01 %s-REC.\n", s->record);
    for (i = 0; i < s->field_count; i++) {
        fprintf(f, "          05 %-20s PIC %s.\n", s->fields[i].name, s->fields[i].pic);
    }
    fprintf(f, "       PROCEDURE DIVISION.\n");
    fprintf(f, "           DISPLAY '%s GENERATED BY GNX'.\n", s->record);
    fprintf(f, "           GOBACK.\n");

    fclose(f);
    printf("gnx: generated %s\n", out_path);
    return 0;
}

static int cmd_transpile(int argc, char **argv) {
    const char *spec = NULL;
    const char *out_dir = "cobol/gen";
    spec_t s;
    int i;

    for (i = 0; i < argc; i++) {
        if (strcmp(argv[i], "--out") == 0 && i + 1 < argc) {
            out_dir = argv[++i];
        } else if (argv[i][0] != '-') {
            spec = argv[i];
        }
    }

    if (!spec) {
        fprintf(stderr, "gnx: transpile requires a spec file\n");
        return 1;
    }

    if (parse_spec(spec, &s) != 0) return 1;
    return emit_cobol(&s, out_dir);
}

static int cmd_build(void) {
    printf("gnx: pseudo-build completed (transpile artifacts ready in cobol/gen)\n");
    return 0;
}

static int cmd_run_smoke(void) {
    if (access("cobol/gen", F_OK) != 0) {
        fprintf(stderr, "gnx: missing cobol/gen, run transpile first\n");
        return 1;
    }
    printf("gnx: smoke ok (artifacts present)\n");
    return 0;
}

static int cmd_package(void) {
    int rc = system("tar -czf artifacts/gnx-bundle.tgz cobol/gen sql/schema_v1.sql >/dev/null 2>&1");
    if (rc != 0) {
        fprintf(stderr, "gnx: package failed\n");
        return 1;
    }
    printf("gnx: packaged artifacts/gnx-bundle.tgz\n");
    return 0;
}

static void usage(void) {
    printf("Usage: gnx <command> [args]\n");
    printf("Commands:\n");
    printf("  init\n");
    printf("  parse <spec.gnx>\n");
    printf("  transpile <spec.gnx> [--out <dir>]\n");
    printf("  build\n");
    printf("  run-smoke\n");
    printf("  package\n");
}

int main(int argc, char **argv) {
    if (argc < 2) {
        usage();
        return 1;
    }

    if (strcmp(argv[1], "init") == 0) return cmd_init();
    if (strcmp(argv[1], "parse") == 0) {
        if (argc < 3) {
            fprintf(stderr, "gnx: parse requires spec path\n");
            return 1;
        }
        return cmd_parse(argv[2]);
    }
    if (strcmp(argv[1], "transpile") == 0) return cmd_transpile(argc - 2, &argv[2]);
    if (strcmp(argv[1], "build") == 0) return cmd_build();
    if (strcmp(argv[1], "run-smoke") == 0) return cmd_run_smoke();
    if (strcmp(argv[1], "package") == 0) return cmd_package();

    usage();
    return 1;
}
