CREATE TABLE IF NOT EXISTS araldica (
  id_araldica TEXT PRIMARY KEY, -- COBOL=DB-ID-ARALDICA PIC X(32) PK
  id_famiglia TEXT, -- COBOL=DB-ID-FAMIGLIA PIC X(32) FK=FAMIGLIE(DB-ID-FAMIGLIA)
  blasonatura TEXT, -- COBOL=DB-BLASONATURA PIC X(512)
  url_stemma TEXT, -- COBOL=DB-URL-STEMMA PIC X(256)
  note_araldica TEXT -- COBOL=DB-NOTE-ARALDICA PIC X(512)
);
