CREATE TABLE IF NOT EXISTS famiglie (
  id_famiglia TEXT PRIMARY KEY, -- COBOL=DB-ID-FAMIGLIA PIC X(32) PK
  nome_famiglia TEXT NOT NULL, -- COBOL=DB-NOME-FAMIGLIA PIC X(80)
  categoria_famiglia TEXT, -- COBOL=DB-CATEGORIA-FAMIGLIA PIC X(32)
  blasonatura TEXT, -- COBOL=DB-BLASONATURA PIC X(512)
  note_famiglia TEXT -- COBOL=DB-NOTE-FAMIGLIA PIC X(512)
);
