CREATE TABLE IF NOT EXISTS figliazioni (
  id_figliazione TEXT PRIMARY KEY, -- COBOL=DB-ID-FIGLIAZIONE PIC X(32) PK
  id_figlio TEXT, -- COBOL=DB-ID-FIGLIO PIC X(32) FK=PERSONE(DB-ID-PERSONA)
  id_genitore TEXT, -- COBOL=DB-ID-GENITORE PIC X(32) FK=PERSONE(DB-ID-PERSONA)
  relazione_parentela TEXT, -- COBOL=DB-RELAZIONE-PARENTELA PIC X(16)
  note_figliazione TEXT -- COBOL=DB-NOTE-FIGLIAZIONE PIC X(512)
);
