CREATE TABLE IF NOT EXISTS fonti (
  id_fonte TEXT PRIMARY KEY, -- COBOL=DB-ID-FONTE PIC X(32) PK
  tipo_fonte TEXT, -- COBOL=DB-TIPO-FONTE PIC X(40)
  riferimento_fonte TEXT, -- COBOL=DB-RIFERIMENTO-FONTE PIC X(256)
  url_fonte TEXT, -- COBOL=DB-URL-FONTE PIC X(256)
  note_fonte TEXT -- COBOL=DB-NOTE-FONTE PIC X(512)
);
