CREATE TABLE IF NOT EXISTS matrimoni (
  id_matrimonio TEXT PRIMARY KEY, -- COBOL=DB-ID-MATRIMONIO PIC X(32) PK
  id_persona_sposo TEXT, -- COBOL=DB-ID-PERSONA-SPOSO PIC X(32) FK=PERSONE(DB-ID-PERSONA)
  id_persona_sposa TEXT, -- COBOL=DB-ID-PERSONA-SPOSA PIC X(32) FK=PERSONE(DB-ID-PERSONA)
  data_matrimonio TEXT, -- COBOL=DB-DATA-MATRIMONIO PIC X(10)
  luogo_matrimonio TEXT, -- COBOL=DB-LUOGO-MATRIMONIO PIC X(80)
  note_matrimonio TEXT -- COBOL=DB-NOTE-MATRIMONIO PIC X(512)
);
