CREATE TABLE IF NOT EXISTS persone (
  id_persona TEXT PRIMARY KEY, -- COBOL=DB-ID-PERSONA PIC X(32) PK
  nome TEXT NOT NULL, -- COBOL=DB-NOME PIC X(60)
  cognome TEXT NOT NULL, -- COBOL=DB-COGNOME PIC X(60)
  data_nascita TEXT, -- COBOL=DB-DATA-NASCITA PIC X(10)
  luogo_nascita TEXT, -- COBOL=DB-LUOGO-NASCITA PIC X(80)
  note TEXT -- COBOL=DB-NOTE PIC X(512)
);
