CREATE TABLE IF NOT EXISTS proprieta (
  id_proprieta TEXT PRIMARY KEY, -- COBOL=DB-ID-PROPRIETA PIC X(32) PK
  id_famiglia TEXT, -- COBOL=DB-ID-FAMIGLIA PIC X(32) FK=FAMIGLIE(DB-ID-FAMIGLIA)
  nome_proprieta TEXT, -- COBOL=DB-NOME-PROPRIETA PIC X(120)
  localita TEXT, -- COBOL=DB-LOCALITA PIC X(120)
  tipologia TEXT, -- COBOL=DB-TIPOLOGIA PIC X(40)
  note_proprieta TEXT -- COBOL=DB-NOTE-PROPRIETA PIC X(512)
);
