CREATE TABLE IF NOT EXISTS titoli (
  id_titolo TEXT PRIMARY KEY, -- COBOL=DB-ID-TITOLO PIC X(32) PK
  id_persona TEXT, -- COBOL=DB-ID-PERSONA PIC X(32) FK=PERSONE(DB-ID-PERSONA)
  id_famiglia TEXT, -- COBOL=DB-ID-FAMIGLIA PIC X(32) FK=FAMIGLIE(DB-ID-FAMIGLIA)
  nome_titolo TEXT NOT NULL, -- COBOL=DB-NOME-TITOLO PIC X(80)
  grado_titolo TEXT, -- COBOL=DB-GRADO-TITOLO PIC X(40)
  note_titolo TEXT -- COBOL=DB-NOTE-TITOLO PIC X(512)
);
